routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function(){
	Route::resource('resturents', 'ResturentsController');
	Route::resource('branches', 'BranchesController');
	Route::resource('departments', 'DepartmentsController');
	Route::resource('locations', 'LocationsController');
});

Route::group(['prefix'=>'admin', 'namespace' => 'Auth'], function(){
	Route::get('login', 'LoginController@showLoginForm')->name('login');
	Route::post('login', 'LoginController@login');
	Route::get('logout', 'LoginController@logout')->name('logout');

	Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset.token');
    Route::post('password/reset', 'ResetPasswordController@reset');
});

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Branch.php
<?php

namespace RMS\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Branch extends Model
{
    // use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = [
    	'name',
    	'address',
    	'email',
    	'contactNo',
    	'resturent_id'
    ];

    public function resturent() {
        return $this->belongsTo('RMS\Models\Resturent');
    }

    public function departments(){
        return $this->belongsToMany('RMS\Models\Department')->withTimestamps();
    }
    
    public function locations() {
        return $this->hasMany('RMS\Models\Location');
    }
}

app/Http/Controllers/Admin/BranchesController.php
<?php

namespace RMS\Http\Controllers\Admin;

use Illuminate\Http\Request;
use RMS\Models\Resturent;
use RMS\Models\Branch;
use RMS\Models\Department;
use RMS\Http\Controllers\Controller;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Database\Query\Builder;
class BranchesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $branches = Branch::all();
        

        $params = [
            'title' => 'Branches List',
            'branches' => $branches,
        ];
        return view('admin.branches.branches_list')->with($params);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $resturents = Resturent::all();
        $departments = Department::all();
        $params = [
            'title' => 'Create Branch',
            'resturents' => $resturents,
            'departments' => $departments,

        ];
        return view('admin.branches.branches_create')->with($params);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // var_dump($request->input('departments'));
        $contactNoString = implode(",", $request->input('contactNo'));
        $departments = $request->input('departments');        

         $branch = Branch::create([
            'name' => $request->input('name'),
            'address' => $request->input('address'),
            'email' => $request->input('email'),
            'contactNo' => $contactNoString,
            'resturent_id' => $request->input('resturent_id'),
        ]);

        $branch->departments()->attach($departments);

        return redirect()->route('branches.index')->with('success', "The branch <strong>$branch->name</strong> has successfully been created.
            ");
       
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        try{
            $branch = Branch::findOrFail($id);

            $params = [
                'title' => 'Delete Branch',
                'branch' => $branch,
            ];

            return view('admin.branches.branches_delete')->with($params);
        }
        catch (ModelNotFoundException $ex) 
        {
            if ($ex instanceof ModelNotFoundException)
            {
                return response()->view('errors.'.'404');
            }
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        try
        {
            $branch = Branch::findOrFail($id);
            $resturents = Resturent::all();
            $departments = Department::all();


            $params = [
                'title' => 'Edit Branch',
                'branch' => $branch,
                'departments' => $departments,
                'resturents' => $resturents,
            ];

            return view('admin.branches.branches_edit')->with($params);
        }
        catch (ModelNotFoundException $ex) 
        {
            if ($ex instanceof ModelNotFoundException)
            {
                return response()->view('errors.'.'404');
            }
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try
        {
            $branch = Branch::findOrFail($id);

            $contactNoString = implode(",", array_filter($request->post('contactNo'),function($val){
                return $val && $val != '';
            }));

            $departments = $request->input('departments');


            $this->validate($request, [
                'name' => 'required',
                'address' => 'required',
                'email' => 'required|unique:branches,email,'.$id,
                'contactNo' => 'required',
                'resturent_id' => 'required',
            ]);

            $branch->name = $request->input('name');
            $branch->address = $request->input('address');
            $branch->email = $request->input('email');
            $branch->contactNo = $contactNoString;
            $branch->resturent_id = $request->input('resturent_id');

            $branch->save();
            $branch->departments();
            $branch->departments()->sync($departments);

            return redirect()->route('branches.index')->with('success', "The branch <strong>$branch->name</strong> has successfully been updated.");
        }
        catch (ModelNotFoundException $ex) 
        {
            if ($ex instanceof ModelNotFoundException)
            {
                return response()->view('errors.'.'404');
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        try
        {
            $branch = Branch::findOrFail($id);

            $branch->delete();

            return redirect()->route('branches.index')->with('success', "The branch <strong>{{$branch->name}}</strong> has successfully been archived.");
        }
        catch (ModelNotFoundException $ex) 
        {
            if ($ex instanceof ModelNotFoundException)
            {
                return response()->view('errors.'.'404');
            }
        }
    }
}

resources/views/admin/branches/branches_create.blade.php
@extends('templates.admin.layout')

@section('content')
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Create Branch <a href="{{route('branches.index')}}" class="btn btn-info btn-xs"><i class="fa fa-chevron-left"></i> Back </a></h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br />
                    <form method="post" action="{{ route('branches.store') }}" data-parsley-validate class="form-horizontal form-label-left">

                        <div class="form-group{{ $errors->has('resturentName') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="resturentName">Branch Name <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('name') ?: '' }}" id="name" name="name" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('name'))
                                <span class="help-block">{{ $errors->first('name') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="address">Address <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('address') ?: '' }}" id="address" name="address" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('address'))
                                <span class="help-block">{{ $errors->first('address') }}</span>
                                @endif
                            </div>
                        </div> 



                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Email <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="email" value="{{ Request::old('email') ?: '' }}" id="email" name="email" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('email'))
                                <span class="help-block">{{ $errors->first('email') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('contactNo') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="contactNo">Contact No <span class="required">*</span>
                            </label>
                            <div class="multi-element-control col-md-6 col-sm-6 col-xs-12">
                                <div class="multi-element entry input-group">
                                    <input type="tel" value="{{ Request::old('contactNo') ?: '' }}" id="contactNo" name="contactNo[]" class="form-control col-md-7 col-xs-12">
                                    <span class="input-group-btn">
                                        <button class="btn btn-success btn-add" type="button">
                                            <span class="glyphicon glyphicon-plus"></span>
                                        </button>
                                    </span>
                                    @if ($errors->has('contactNo'))
                                    <span class="help-block">{{ $errors->first('contactNo') }}</span>
                                    @endif
                                </div>
                            </div>                            
                        </div>

                        

                        <div class="form-group{{ $errors->has('resturent_id') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="resturent_id">Resturent <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <select class="form-control" id="resturent_id" name="resturent_id">
                                    @if(count($resturents))
                                        @foreach($resturents as $row)
                                            <option value="{{$row->id}}">{{$row->name}}</option>
                                        @endforeach
                                    @endif
                                </select>
                                @if ($errors->has('resturent_id'))
                                <span class="help-block">{{ $errors->first('resturent_id') }}</span>
                                @endif
                            </div>
                        </div> 

                        <div class="form-group{{ $errors->has('departments[]') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="departments[]">Depatments <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <div class="panel panel-default">
                                    <!-- Default panel contents -->
                                    <div class="panel-heading">Select Available Departments</div>
                                
                                    <!-- List group -->
                                    <ul class="list-group">
                                        @if(count($departments))
                                            @foreach($departments as $row)
                                                <li class="list-group-item">
                                                    {{$row->name}}
                                                    <div class="material-switch pull-right">
                                                        <input id="departments{{$row->id}}" name="departments[]" type="checkbox" value="{{$row->id}}"/>
                                                        <label for="departments{{$row->id}}" class="label-success"></label>
                                                    </div>
                                                </li>
                                            @endforeach
                                        @endif                                       
                                    </ul>
                                </div>
                            </div>
                        </div>                                 

                        <div class="ln_solid"></div>

                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <input type="hidden" name="_token" value="{{ Session::token() }}">
                                <button type="submit" class="btn btn-success">Create Branch</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/branches/branches_delete.blade.php
@extends('templates.admin.layout')

@section('content')
<div class="">
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Confirm Delete Record <a href="{{route('branches.index')}}" class="btn btn-info btn-xs"><i class="fa fa-chevron-left"></i> Back </a></h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <p>Are you sure you want to delete <strong>Branch</strong></p>

                    <form method="POST" action="{{ route('branches.destroy', ['id' => $branch->id]) }}">
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                        <input name="_method" type="hidden" value="DELETE">
                        <button type="submit" class="btn btn-danger">Yes I'm sure. Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/branches/branches_edit.blade.php
@extends('templates.admin.layout')

@section('content')
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Edit Branch <a href="{{route('branches.index')}}" class="btn btn-info btn-xs"><i class="fa fa-chevron-left"></i> Back </a></h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br />
                    <form method="post" action="{{ route('branches.update', ['id' => $branch->id]) }}" data-parsley-validate class="form-horizontal form-label-left">

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Branch Name <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{$branch->name}}" id="name" name="name" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('name'))
                                <span class="help-block">{{ $errors->first('name') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="address">Address <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{$branch->address}}" id="address" name="address" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('address'))
                                <span class="help-block">{{ $errors->first('address') }}</span>
                                @endif
                            </div>
                        </div> 



                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Email <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="email" value="{{$branch->email}}" id="email" name="email" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('email'))
                                <span class="help-block">{{ $errors->first('email') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('contactNo') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="contactNo">Contact No <span class="required">*</span>
                            </label>
                            <div class="multi-element-control col-md-6 col-sm-6 col-xs-12">
                                <?php
                                    $contactNos = explode(",",$branch->contactNo);
                                ?>
                                @if(count($contactNos))
                                    @foreach($contactNos as $contactNo)
                                        @if($contactNo != '')
                                        <div class="multi-element entry input-group"> 
                                            <input type="tel" value="{{$contactNo}}" id="contactNo" name="contactNo[]" class="form-control col-md-7 col-xs-12">
                                            <span class="input-group-btn">
                                                <button class="btn btn-danger btn-remove" type="button">
                                                    <span class="glyphicon glyphicon-minus"></span>
                                                </button>
                                            </span>
                                            @if ($errors->has('contactNo'))
                                                <span class="help-block">{{ $errors->first('contactNo') }}</span>
                                            @endif
                                        </div>
                                        @endif
                                    @endforeach
                                @endIf
                                <div class="multi-element entry input-group">                                
                                    
                                    <input type="tel" value="{{ Request::old('contactNo') ?: '' }}" id="contactNo" name="contactNo[]" class="form-control col-md-7 col-xs-12">
                                    <span class="input-group-btn">
                                        <button class="btn btn-success btn-add" type="button">
                                            <span class="glyphicon glyphicon-plus"></span>
                                        </button>
                                    </span>
                                    @if ($errors->has('contactNo'))
                                    <span class="help-block">{{ $errors->first('contactNo') }}</span>
                                    @endif
                                </div>
                            </div>                            
                        </div>

                        

                        <div class="form-group{{ $errors->has('resturent_id') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="resturent_id">Resturent <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <select class="form-control" value="{{$branch->resturent_id}}" id="resturent_id" name="resturent_id">
                                    @if(count($resturents))
                                        @foreach($resturents as $row)
                                            <option value="{{$row->id}}" {{$row->id==$branch->resturent->id ? 'selected="selected"' : ''}}>{{$row->name}}</option>
                                        @endforeach
                                    @endif
                                </select>
                                @if ($errors->has('resturent_id'))
                                <span class="help-block">{{ $errors->first('resturent_id') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('departments[]') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="departments[]">Depatments <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <div class="panel panel-default">
                                    <!-- Default panel contents -->
                                    <div class="panel-heading">Select Available Departments</div>
                                
                                    <!-- List group -->
                                    <?php
                                        $availaleDepartmentIds = [];
                                        if(count($branch->departments)){
                                            foreach ($branch->departments as $row) {
                                                array_push($availaleDepartmentIds, $row->id) ;
                                            }
                                        }

                                    ?>
                                    <ul class="list-group">
                                        @if(count($departments))
                                            @foreach($departments as $row)
                                                <li class="list-group-item">
                                                    {{$row->name}}
                                                    <div class="material-switch pull-right">
                                                        <input id="departments{{$row->id}}"  name="departments[]" type="checkbox" value="{{$row->id}}" {{in_array($row->id, $availaleDepartmentIds) ? 'checked' : ''}}/>
                                                        <label for="departments{{$row->id}}" class="label-success"></label>
                                                    </div>
                                                </li>
                                            @endforeach
                                        @endif                                       
                                    </ul>
                                </div>
                            </div>
                        </div> 

                        <div class="ln_solid"></div>

                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <input type="hidden" name="_token" value="{{ Session::token() }}">
                                <input name="_method" type="hidden" value="PUT">
                                <button type="submit" class="btn btn-success">Save Branch Changes</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/branches/branches_list.blade.php
@extends('templates.admin.layout')

@section('content')
<div class="">

    <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Branches <a href="{{route('branches.create')}}" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i> Create New </a></h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Address</th>
                                <th>Email</th>
                                <th>Contact Nos</th>
                                <th>Resturent</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Name</th>
                                <th>Address</th>
                                <th>Email</th>
                                <th>Contact Nos</th>
                                <th>Resturent</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            <!-- {{$branches}} -->
                            @if (count($branches))
                            @foreach($branches as $row)
                            <tr>
                                <td>{{$row->name}}</td>                   
                                <td>{{$row->address}}</td>
                                <td>{{$row->email}}</td>
                                <td>{{$row->contactNo}}</td>
                                <td>{{$row->resturent->name}}</td>
                                <td>
                                    <a href="{{ route('branches.edit', ['id' => $row->id]) }}" class="btn btn-info btn-xs"><i class="fa fa-pencil" title="Edit"></i> </a>
                                    <a href="{{ route('branches.show', ['id' => $row->id]) }}" class="btn btn-danger btn-xs"><i class="fa fa-trash-o" title="Delete"></i> </a>
                                </td>
                            </tr>
                            @endforeach
                            @endif
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop